# Generated by Django 5.1 on 2024-08-16 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claimManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='policy',
            name='policy_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
